---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:day ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "Avi Srivastava"
keywords:    "Avi, computational biology, genomics, transcriptomics"
description: "Persomal Page of Avi Srivastava"
source_link: "https://github.com/keyavi/keyavi.github.io"
favicon:     "img/favicon.ico" #put a path like: "img/favicon.ico"
touch_icon:  "img/apple.png" #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f1eed9'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  textbg:    '#46433A'
  garnet:    '#782F40'
  gold:      '#CEB888'

